### ISSUE TITLE
Surface the build version in the application for logging etc

### ISSUE THREAD

**Issue by ChristopherJamesMorris** [nhsconnect/gpconnect-appointment-checker#111]
Use the version from the Docker Container to indicate which version of the application is being used.

Ideally add it to Logging and somewhere in the UI.

**Comment by jonnyry** [comment]
Due to the challenges in communicating with the Docker API in all environments, this now uses an environment variable called BUILD_TAG which is generated in the GitHub build scripts, and inserted into the Docker Container when the container is built using a build arg.

Example build tag:  `gpconnect-appointment-checker | Branch master | SHA 083c1c8 | BuildTime 2021-03-10T17:07:04`

If the BUILD_TAG is not set (e.g. because the application is built locally), the application uses the dotnet assembly details as before.

**Comment by jonnyry** [comment]
As before, the application version (from the BUILD_TAG) is set in the logging.error_log table for every log entry.

No change has been made to put the version in the UI at present.
